id: P009590
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:37.480282
source_metadata:
  id: bdr:W1PD181178
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། རྟ་མགྲིན་དྲེགས་ཟིལ་གྱི་སྐོར།
  author: ''
  volumes:
    a2c24ea1297847feb875d1eee80716fa:
      image_group_id: I1KG16351
      title: ''
      volume_number: 1
      total_pages: 408
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
