id: P009590
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181178
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། རྟ་མགྲིན་དྲེགས་ཟིལ་གྱི་སྐོར།
  author: ''
  volumes:
    a2c24ea1297847feb875d1eee80716fa:
      image_group_id: I1KG16351
      title: ''
      volume_number: 1
      total_pages: 408
      base_file: v001.txt
